name: Pre-Commit

on: [push, pull_request]

jobs:
  Pre-Commit:
    name: Run Pre-Commit

    runs-on: ubuntu-latest

    container:
      image: python:3.8-slim-bullseye

    steps:

    - name: Install System Deps
      run: |
        apt-get update
        apt-get install -y git libcurl4-openssl-dev gcc libssl-dev libmagic1

    - uses: actions/checkout@v2

    - name: Set Pre-Commit Cache Key
      run: echo "PY=$(python --version --version | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

    - name: Setup Pre-Commit Cache
      uses: pat-s/always-upload-cache@v2.1.3
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

    - id: changed-files
      name: Get Changed Files
      uses: dorny/paths-filter@v2
      with:
        token: ${{ github.token }}
        list-files: json
        filters: |
          repo:
            - added|modified:
              - '**'

    - name: Check Changed Files
      uses: pre-commit/action@v2.0.0
      if: steps.changed-files.outputs.repo == 'true'
      with:
        extra_args: --verbose --files ${{ join(fromJSON(steps.changed-files.outputs.repo_files), ' ') }}
